"use client";

import React from 'react';
import Link from 'next/link';
import { Shield, Fingerprint, Lock, Globe, Database, ArrowRight } from 'lucide-react';

export default function AboutPage() {
  return (
    <div className="min-h-screen bg-base pt-48 pb-32 px-6">
      <div className="max-w-3xl mx-auto space-y-24">
        
        <header className="space-y-6">
          <h1 className="text-5xl md:text-6xl font-bold tracking-tight">The Protocol.</h1>
          <p className="text-xl text-secondary leading-relaxed">
            Relay was engineered to provide researchers with a transparent and ethical framework 
            for open-source intelligence discovery. 
          </p>
        </header>

        <div className="divider" />

        <div className="space-y-16">
          <section className="space-y-6">
            <h2 className="text-xs font-black uppercase tracking-[0.2em] text-muted">Core Objectives</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-12">
              <Objective 
                icon={<Fingerprint className="w-5 h-5 text-white" />}
                title="Attributable Discovery"
                text="Every correlation generated by Relay points directly to its original public source. We prioritize data provenance over volume."
              />
              <Objective 
                icon={<Lock className="w-5 h-5 text-white" />}
                title="Stateless Architecture"
                text="The platform possesses no capability for persistent data storage. Queries exist in memory only during active execution."
              />
              <Objective 
                icon={<Globe className="w-5 h-5 text-white" />}
                title="Ethical Boundaries"
                text="Relay aggregates publicly available information only. We do not support methods that bypass private data protections."
              />
              <Objective 
                icon={<Database className="w-5 h-5 text-white" />}
                title="Open Source"
                text="The Community Edition is fully transparent and MIT licensed. Auditable logic ensures the tool remains neutral."
              />
            </div>
          </section>

          <section className="glass-card p-12 space-y-8 bg-surface/30">
            <h2 className="text-2xl font-bold">Investigation Standards</h2>
            <div className="space-y-6">
              <p className="text-secondary leading-relaxed">
                As an investigative instrument, Relay is designed to be used by researchers who value 
                accuracy and data integrity. We emphasize a conservative matching logic to minimize 
                noise and increase the reliability of findings.
              </p>
              <div className="flex flex-wrap gap-4 pt-4">
                <Link href="/scan" className="btn-primary text-sm">Open Scanner</Link>
                <Link href="/ecosystem" className="btn-secondary text-sm">Tier Comparison</Link>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
}

function Objective({ icon, title, text }: { icon: React.ReactNode, title: string, text: string }) {
  return (
    <div className="space-y-4">
      <div className="w-10 h-10 rounded-lg bg-surface border border-border-strong flex items-center justify-center">
        {icon}
      </div>
      <h3 className="text-lg font-bold">{title}</h3>
      <p className="text-sm text-secondary leading-relaxed">{text}</p>
    </div>
  );
}
